
@baseUrl = http://localhost:8081

### Get Auth Token
# @name auth
GET {{baseUrl}}/tokenz

###

@token = {{auth.response.body.$.token}}

### Delete Todo
DELETE {{baseUrl}}/todos/4
Content-Type: application/json
Authorization: Bearer {{token}}